services:
  frontend:
    build:
      context: ./frontend/mycelium
      dockerfile: Dockerfile
      args:
        - BACKEND_HOST=${BACKEND_HOST:-backend}
        - BACKEND_PORT=${BACKEND_PORT:-8000}
        - FRONTEND_PORT=${FRONTEND_PORT:-80}
        - FRONTEND_HOST=${FRONTEND_HOST:-0.0.0.0}
        - SUPABASE_URL=${SUPABASE_URL}
        - SUPABASE_KEY=${SUPABASE_KEY}
    container_name: frontend
    ports:
      - "${FRONTEND_PORT:-80}:80"
    networks:
      - shared-network
    depends_on:
      - backend
    env_file:
      - .env

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      args:
        - BACKEND_HOST=${BACKEND_HOST:-0.0.0.0}
        - BACKEND_PORT=${BACKEND_PORT:-8000}
        - DATABASE_TYPE=${DATABASE_TYPE:-supabase}
        - SUPABASE_URL=${SUPABASE_URL}
        - SUPABASE_KEY=${SUPABASE_KEY}
    container_name: backend
    ports:
      - "${BACKEND_PORT:-8000}:8000"
    networks:
      - shared-network
    depends_on:
      - supabase
    env_file:
      - .env
    environment:
      - DATABASE_TYPE=${DATABASE_TYPE:-supabase}
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_KEY=${SUPABASE_KEY}

  supabase:
    extends:
      file: ./backend/supabase/docker-compose.yml
      service: supabase
    networks:
      - shared-network

networks:
  shared-network:
    driver: bridge

volumes:
  supabase-data:
    driver: local
