version: '3.8'

services:
  supabase:
    image: supabase/supabase-local:latest
    ports:
      - "54321:54321"  # REST API
      - "54322:54322"  # Studio
      - "54323:54323"  # Inbucket
      - "54324:54324"  # Authentication
      - "54325:54325"  # Realtime
      - "54326:54326"  # Storage
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      JWT_SECRET: ${SUPABASE_JWT_SECRET}
      DASHBOARD_USERNAME: ${DASHBOARD_USERNAME}
      DASHBOARD_PASSWORD: ${DASHBOARD_PASSWORD}
      STUDIO_PORT: 54322
      API_PORT: 54321
      DB_PORT: 54320
      KONG_PORT: 54321
      SUPABASE_URL: ${SUPABASE_URL}
      SUPABASE_KEY: ${SUPABASE_KEY}
      SUPABASE_JWT_SECRET: ${SUPABASE_JWT_SECRET}
    volumes:
      - supabase-data:/var/lib/postgresql/data
    networks:
      - supabase-network

networks:
  supabase-network:
    driver: bridge

volumes:
  supabase-data:
    driver: local 