version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - BACKEND_PORT=${BACKEND_PORT:-8000}
        - SUPABASE_URL=${SUPABASE_URL}
        - SUPABASE_KEY=${SUPABASE_KEY}
    ports:
      - "${BACKEND_PORT:-8000}:8000"
    volumes:
      - .:/app
    environment:
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_KEY=${SUPABASE_KEY}
      - SECRET_KEY=${SECRET_KEY}
    depends_on:
      - supabase
    networks:
      - backend-network

  supabase:
    image: supabase/supabase-local:latest
    ports:
      - "54321:54321"  # REST API
      - "54322:54322"  # Studio
      - "54323:54323"  # Inbucket
      - "54324:54324"  # Authentication
      - "54325:54325"  # Realtime
      - "54326:54326"  # Storage
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-your-super-secret-password}
      JWT_SECRET: ${SUPABASE_JWT_SECRET:-your-super-secret-jwt-token}
      DASHBOARD_USERNAME: ${DASHBOARD_USERNAME:-admin}
      DASHBOARD_PASSWORD: ${DASHBOARD_PASSWORD:-admin}
      SUPABASE_URL: ${SUPABASE_URL:-http://localhost:54321}
      SUPABASE_KEY: ${SUPABASE_KEY:-your-supabase-anon-key}
      SUPABASE_JWT_SECRET: ${SUPABASE_JWT_SECRET:-your-super-secret-jwt-token}
    volumes:
      - supabase-data:/var/lib/postgresql/data
    networks:
      - backend-network

networks:
  backend-network:
    driver: bridge

volumes:
  supabase-data:
    driver: local