name: "Oracle Database Source"
description: "Template for Oracle database connections and table extractions"
tabs:
  info:
    label: "Information"
    description: "Basic information about the data contract"
    fields:
      - name: "title"
        label: "Title"
        type: "text"
        required: true
        placeholder: "My Oracle Data Contract"
        hint: "A descriptive name for this data contract"
      
      - name: "version"
        label: "Version"
        type: "text"
        required: true
        pattern: "^\\d+\\.\\d+\\.\\d+$"
        placeholder: "1.0.0"
        hint: "Semantic version (e.g. 1.0.0)"
      
      - name: "description"
        label: "Description"
        type: "textarea"
        required: true
        rows: 4
        hint: "Detailed description of this data contract"

      - name: "owner"
        label: "Owner"
        type: "text"
        required: true
        hint: "Team or person responsible for this data contract"

  source:
    label: "Source"
    description: "Oracle database connection details"
    fields:
      - name: "host"
        label: "Host"
        type: "text"
        required: true
        placeholder: "db.example.com"
        hint: "Database server hostname or IP address"

      - name: "port"
        label: "Port"
        type: "number"
        required: true
        default: 1521
        min: 1
        max: 65535
        hint: "Database server port (default: 1521)"

      - name: "service_name"
        label: "Service Name"
        type: "text"
        required: true
        hint: "Oracle service name"

      - name: "username"
        label: "Username"
        type: "text"
        required: true
        hint: "Database user account"

      - name: "password_secret_id"
        label: "Password Secret ID"
        type: "text"
        required: true
        hint: "Secret ID for database password in secret manager"

  schema:
    label: "Schema"
    description: "Configuration for data extraction"
    fields:
      - name: "schedule"
        label: "Schedule"
        type: "text"
        required: true
        placeholder: "0 4 * * *"
        hint: "Cron expression for scheduling extractions"

      - name: "table"
        label: "Source Table"
        type: "text"
        required: true
        placeholder: "SCHEMA.TABLE_NAME"
        hint: "Fully qualified table name to extract from"

      - name: "bucket_name"
        label: "Bucket Name"
        type: "text"
        required: true
        hint: "GCS bucket name for storing extracted data"

  compute:
    label: "Compute"
    description: "Compute resources for extraction"
    fields:
      - name: "memory_limit"
        label: "Memory Limit (GB)"
        type: "number"
        default: 4
        min: 1
        max: 16
        hint: "Memory limit in gigabytes"

      - name: "cpu_limit"
        label: "CPU Limit"
        type: "number"
        default: 1
        min: 0.1
        max: 4
        hint: "CPU cores limit"