site_name: "Mycelium Backend Documentation"
theme:
  name: "material"
  palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep purple
      accent: amber
      toggle:
        icon: material/lightbulb-outline
        name: "Switch to light mode"
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: deep purple
      accent: amber
      toggle:
        icon: material/lightbulb
        name: "Switch to dark mode"
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  icon:
    repo: fontawesome/brands/github
  repo_name: ThomasGraff/mycelium
  repo_url: https://github.com/ThomasGraff/mycelium

nav:
  - Get started:
    - Welcome to mycelium: home/welcome.md
    - Why use Mycelium?: home/why.md
  - Data Contract Models:
    - DataContract: data_contract_models/data_contract.md
    - InfoObject: data_contract_models/info_object.md
    - ServerObject: data_contract_models/server_object.md
    - TermObject: data_contract_models/term_object.md
    - ModelObject: data_contract_models/model_object.md
    - DefinitionObject: data_contract_models/definition_object.md
    - ExampleObject: data_contract_models/example_object.md
    - ServiceLevelObject: data_contract_models/service_level_object.md
    - QualityObject: data_contract_models/quality_object.md
  - API Endpoints:
    - Get Data Contracts: api_endpoints/get_data_contracts.md
    - List Data Contracts: api_endpoints/list_data_contracts.md
    - Create Data Contract: api_endpoints/create_data_contract.md
    - Update Data Contract: api_endpoints/update_data_contract.md
    - Delete Data Contract: api_endpoints/delete_data_contract.md

markdown_extensions:
  - tables
  - toc:
      permalink: true
      title: Page contents
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.extra
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - md_in_html

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: ["../backend/app/schemas/"]
          options:
            show_bases: false
            members_order: source
            separate_signature: true
            filters: ["!^_"]
            docstring_options:
              ignore_init_summary: true
            merge_init_into_class: true
            show_signature_annotations: true
            signature_crossrefs: true
            show_if_no_docstring: true
            show_root_heading: true
            inherited_members: true
            unwrap_annotated: true
            docstring_section_style: spacy
            show_symbol_type_heading: true
            show_symbol_type_toc: true
            extensions:
            - griffe_typingdoc



extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/ThomasGraff/mycelium

copyright: "&copy; 2023 Mycelium Project"
