name: CI/CD Frontend

on:
  push:
    paths:
      - 'frontend/**'  # Déclenche le workflow uniquement si des fichiers dans le dossier frontend sont modifiés
  pull_request:
    paths:
      - 'frontend/**'  # Déclenche le workflow pour les PR affectant le dossier frontend

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build frontend Docker image
        run: |
          docker build -t mon-frontend ./frontend

      - name: Run tests (optionnel)
        working-directory: ./frontend
        run: |
          # Ajoutez des tests ici si nécessaire
          echo "No tests configured."

      - name: Run Docker container
        run: |
          docker run -d -p 80:80 --name frontend_container mon-frontend

      - name: Deploy frontend (exemple)
        run: |
          # Remplacez par vos commandes de déploiement, par exemple
          echo "Déploiement du frontend (ajoutez vos commandes de déploiement ici)"
